package org.comcom.dto;

public enum Roles {
    ANONYMOUS,
    CUSTOMER,
    INTERPRETER,
    CAPTIONER,
    COMPANY_EMPLOYEE,
    COMPANY_LEADER,
    SWITCHING_CENTER_EMPLOYEE,
    SWITCHING_CENTER_LEADER,
    COMMUNICATION_ASSISTANCE,
    ADMIN
}
